import { UserActivityRecord, OutcomeConfidenceRecord } from '../types/reports';

// Mock User Activity Data
export const MOCK_USER_ACTIVITY: UserActivityRecord[] = [
  {
    id: 'ua-1',
    userId: 'user-admin-1',
    displayName: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    role: 'admin',
    lastVisit: '2024-01-18T09:30:00Z',
    visitCount: 45,
    daysSinceLastVisit: 0,
    assessmentsCreated: 12,
    assessmentsViewed: 87,
    avgSessionMinutes: 23,
  },
  {
    id: 'ua-2',
    userId: 'user-admin-2',
    displayName: 'Michael Torres',
    email: 'michael.torres@company.com',
    role: 'admin',
    lastVisit: '2024-01-17T14:15:00Z',
    visitCount: 38,
    daysSinceLastVisit: 1,
    assessmentsCreated: 8,
    assessmentsViewed: 65,
    avgSessionMinutes: 18,
  },
  {
    id: 'ua-3',
    userId: 'user-creator-1',
    displayName: 'Emily Park',
    email: 'emily.park@company.com',
    role: 'creator',
    lastVisit: '2024-01-16T11:00:00Z',
    visitCount: 22,
    daysSinceLastVisit: 2,
    assessmentsCreated: 15,
    assessmentsViewed: 34,
    avgSessionMinutes: 31,
  },
  {
    id: 'ua-4',
    userId: 'user-creator-2',
    displayName: 'David Kim',
    email: 'david.kim@company.com',
    role: 'creator',
    lastVisit: '2024-01-10T16:45:00Z',
    visitCount: 8,
    daysSinceLastVisit: 8,
    assessmentsCreated: 3,
    assessmentsViewed: 12,
    avgSessionMinutes: 15,
  },
  {
    id: 'ua-5',
    userId: 'user-creator-3',
    displayName: 'Jessica Williams',
    email: 'jessica.williams@company.com',
    role: 'creator',
    lastVisit: '2024-01-15T08:20:00Z',
    visitCount: 28,
    daysSinceLastVisit: 3,
    assessmentsCreated: 9,
    assessmentsViewed: 41,
    avgSessionMinutes: 22,
  },
  {
    id: 'ua-6',
    userId: 'user-viewer-1',
    displayName: 'Alex Johnson',
    email: 'alex.johnson@company.com',
    role: 'viewer',
    lastVisit: '2024-01-14T13:30:00Z',
    visitCount: 15,
    daysSinceLastVisit: 4,
    assessmentsCreated: 0,
    assessmentsViewed: 28,
    avgSessionMinutes: 8,
  },
  {
    id: 'ua-7',
    userId: 'user-viewer-2',
    displayName: 'Chris Martinez',
    email: 'chris.martinez@company.com',
    role: 'viewer',
    lastVisit: '2024-01-05T10:00:00Z',
    visitCount: 5,
    daysSinceLastVisit: 13,
    assessmentsCreated: 0,
    assessmentsViewed: 8,
    avgSessionMinutes: 5,
  },
  {
    id: 'ua-8',
    userId: 'user-viewer-3',
    displayName: 'Rachel Green',
    email: 'rachel.green@company.com',
    role: 'viewer',
    lastVisit: '2023-12-28T09:15:00Z',
    visitCount: 2,
    daysSinceLastVisit: 21,
    assessmentsCreated: 0,
    assessmentsViewed: 3,
    avgSessionMinutes: 4,
  },
  {
    id: 'ua-9',
    userId: 'user-viewer-4',
    displayName: 'Tom Wilson',
    email: 'tom.wilson@company.com',
    role: 'viewer',
    lastVisit: '2024-01-12T15:45:00Z',
    visitCount: 12,
    daysSinceLastVisit: 6,
    assessmentsCreated: 0,
    assessmentsViewed: 19,
    avgSessionMinutes: 11,
  },
  {
    id: 'ua-10',
    userId: 'user-creator-4',
    displayName: 'Amanda Lee',
    email: 'amanda.lee@company.com',
    role: 'creator',
    lastVisit: '2024-01-17T10:30:00Z',
    visitCount: 31,
    daysSinceLastVisit: 1,
    assessmentsCreated: 11,
    assessmentsViewed: 52,
    avgSessionMinutes: 27,
  },
];

// Mock Outcome Confidence Data
export const MOCK_OUTCOME_CONFIDENCE: OutcomeConfidenceRecord[] = [
  // Payments Core
  {
    id: 'oc-1',
    teamId: 'team-1',
    teamName: 'Payments Core',
    outcomeArea: 'commitments',
    confidenceLevel: 'high',
    score: 78,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-2',
    teamId: 'team-1',
    teamName: 'Payments Core',
    outcomeArea: 'productivity',
    confidenceLevel: 'moderate',
    score: 62,
    hasCriticalGap: false,
    blockingDimensions: ['Sprint Predictability'],
  },
  {
    id: 'oc-3',
    teamId: 'team-1',
    teamName: 'Payments Core',
    outcomeArea: 'awareness',
    confidenceLevel: 'high',
    score: 81,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-4',
    teamId: 'team-1',
    teamName: 'Payments Core',
    outcomeArea: 'progress',
    confidenceLevel: 'very-high',
    score: 89,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-5',
    teamId: 'team-1',
    teamName: 'Payments Core',
    outcomeArea: 'collaboration',
    confidenceLevel: 'high',
    score: 75,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  // Identity Services
  {
    id: 'oc-6',
    teamId: 'team-2',
    teamName: 'Identity Services',
    outcomeArea: 'commitments',
    confidenceLevel: 'moderate',
    score: 55,
    hasCriticalGap: true,
    blockingDimensions: ['Backlog & Requirements Maturity'],
  },
  {
    id: 'oc-7',
    teamId: 'team-2',
    teamName: 'Identity Services',
    outcomeArea: 'productivity',
    confidenceLevel: 'low',
    score: 38,
    hasCriticalGap: true,
    blockingDimensions: ['Sprint Predictability', 'Delivery Throughput'],
  },
  {
    id: 'oc-8',
    teamId: 'team-2',
    teamName: 'Identity Services',
    outcomeArea: 'awareness',
    confidenceLevel: 'moderate',
    score: 58,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-9',
    teamId: 'team-2',
    teamName: 'Identity Services',
    outcomeArea: 'progress',
    confidenceLevel: 'moderate',
    score: 61,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-10',
    teamId: 'team-2',
    teamName: 'Identity Services',
    outcomeArea: 'collaboration',
    confidenceLevel: 'high',
    score: 72,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  // Search Team
  {
    id: 'oc-11',
    teamId: 'team-3',
    teamName: 'Search Team',
    outcomeArea: 'commitments',
    confidenceLevel: 'very-high',
    score: 91,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-12',
    teamId: 'team-3',
    teamName: 'Search Team',
    outcomeArea: 'productivity',
    confidenceLevel: 'high',
    score: 84,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-13',
    teamId: 'team-3',
    teamName: 'Search Team',
    outcomeArea: 'awareness',
    confidenceLevel: 'very-high',
    score: 88,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-14',
    teamId: 'team-3',
    teamName: 'Search Team',
    outcomeArea: 'progress',
    confidenceLevel: 'high',
    score: 79,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-15',
    teamId: 'team-3',
    teamName: 'Search Team',
    outcomeArea: 'collaboration',
    confidenceLevel: 'moderate',
    score: 64,
    hasCriticalGap: false,
    blockingDimensions: ['Team Collaboration'],
  },
  // Checkout Flow
  {
    id: 'oc-16',
    teamId: 'team-4',
    teamName: 'Checkout Flow',
    outcomeArea: 'commitments',
    confidenceLevel: 'low',
    score: 42,
    hasCriticalGap: true,
    blockingDimensions: ['Backlog & Requirements Maturity', 'Issue Hygiene'],
  },
  {
    id: 'oc-17',
    teamId: 'team-4',
    teamName: 'Checkout Flow',
    outcomeArea: 'productivity',
    confidenceLevel: 'low',
    score: 35,
    hasCriticalGap: true,
    blockingDimensions: ['Sprint Predictability'],
  },
  {
    id: 'oc-18',
    teamId: 'team-4',
    teamName: 'Checkout Flow',
    outcomeArea: 'awareness',
    confidenceLevel: 'moderate',
    score: 52,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-19',
    teamId: 'team-4',
    teamName: 'Checkout Flow',
    outcomeArea: 'progress',
    confidenceLevel: 'low',
    score: 41,
    hasCriticalGap: true,
    blockingDimensions: ['Flow Efficiency', 'Delivery Throughput'],
  },
  {
    id: 'oc-20',
    teamId: 'team-4',
    teamName: 'Checkout Flow',
    outcomeArea: 'collaboration',
    confidenceLevel: 'moderate',
    score: 58,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  // Mobile Experience
  {
    id: 'oc-21',
    teamId: 'team-7',
    teamName: 'Mobile Experience',
    outcomeArea: 'commitments',
    confidenceLevel: 'high',
    score: 76,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-22',
    teamId: 'team-7',
    teamName: 'Mobile Experience',
    outcomeArea: 'productivity',
    confidenceLevel: 'high',
    score: 71,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-23',
    teamId: 'team-7',
    teamName: 'Mobile Experience',
    outcomeArea: 'awareness',
    confidenceLevel: 'moderate',
    score: 63,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-24',
    teamId: 'team-7',
    teamName: 'Mobile Experience',
    outcomeArea: 'progress',
    confidenceLevel: 'high',
    score: 74,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
  {
    id: 'oc-25',
    teamId: 'team-7',
    teamName: 'Mobile Experience',
    outcomeArea: 'collaboration',
    confidenceLevel: 'very-high',
    score: 86,
    hasCriticalGap: false,
    blockingDimensions: [],
  },
];

// Helper functions
export function getUserActivityByRole(role: UserActivityRecord['role']): UserActivityRecord[] {
  return MOCK_USER_ACTIVITY.filter(u => u.role === role);
}

export function getInactiveUsers(daysSinceLastVisit: number): UserActivityRecord[] {
  return MOCK_USER_ACTIVITY.filter(u => u.daysSinceLastVisit >= daysSinceLastVisit);
}

export function getPowerUsers(minVisits: number = 20): UserActivityRecord[] {
  return MOCK_USER_ACTIVITY.filter(u => u.visitCount >= minVisits);
}

export function getOutcomeConfidenceByTeam(teamId: string): OutcomeConfidenceRecord[] {
  return MOCK_OUTCOME_CONFIDENCE.filter(oc => oc.teamId === teamId);
}

export function getTeamsWithCriticalGaps(): OutcomeConfidenceRecord[] {
  return MOCK_OUTCOME_CONFIDENCE.filter(oc => oc.hasCriticalGap);
}

export function getLowConfidenceOutcomes(): OutcomeConfidenceRecord[] {
  return MOCK_OUTCOME_CONFIDENCE.filter(oc => oc.confidenceLevel === 'low');
}
